name: auth_example
description: A simple example on how to do authentication and authorization with Redstone.dart
dependencies:
  browser: any
  redstone: '>=0.5.0 <1.0.0'
  mongo_dart: any
  crypto: any
  shelf_static: any